### ISSUE TITLE
Print Friendly Notebook Layout

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/node-red-dashboard#166]
### Description

Consider how print-friendly the Notebook layout is, as it could be a use case to print out reports generated by Dashboard.

First mentioned [here](https://github.com/flowforge/flowforge-nr-dashboard/pull/165#issuecomment-1702356074)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
We can define print-only CSS using a Media Query, e.g:

```css
@media print and (orientation: portrait) {
    .nrdb-layout--notebook {
        max-width: 21cm;
        background-color: red;
    }
}
@media print and (orientation: landscape) {
    .nrdb-layout--notebook {
        max-width: 29.7cm;
    }
}
```

However, these didn't seem to get applied correctly, as any chart contained would always push too wide. Colours for widgets (e.g. header background, slider track) also didn't render correctly in the print, so there is likely quite a bit of CSS fiddling to be done here.
