### ISSUE TITLE
Custom icon size in side bar

### ISSUE THREAD

**Issue by postlund** [FlowFuse/node-red-dashboard#955]
### Description

I'm building a dashboard used inside a car with a touch display. To navigate between pages I only display icons in the side bar, but as they are quite small they are a bit finicky to press with a finger. Would it be possible to configure a custom size, to make them a bit bigger for this use case?

### Have you provided an initial effort estimate for this issue?

I am no FlowFuse team member

**Comment by joepavitt** [comment]
This can be done by defining some overriding CSS in a `ui-template` node. Having a quick play, I can see the following would be required:

1. Make the icon larger:

```css
.v-navigation-drawer .v-icon {
    font-size: 3rem;
}
```

2. Make the side navigation drawer wider to accommodate the icons:

```css
.v-navigation-drawer {
    width: 6rem !important;
}
```

3. Shift the `main` Dashboard content over to account for the width of the sidebar now:

```css
.v-main {
    --v-layout-left: 6rem !important;
}
```

Important is required here because Vuetify will set the width via JavaScript, accounting for opening/closing the sidebar, in your case, I understand you'd want that a fixed width?

4. Hide the text labels for each page, as Vuetify just cuts them off when in "icon only" mode, again, here I understand you want them hidden:

```css
.v-list-item__content {
    display: none
}
```

Hope that helps!
