### ISSUE TITLE
Item text not showing in dropdown menus

### ISSUE THREAD

**Issue by postlund** [FlowFuse/node-red-dashboard#986]
### Current Behavior

I believe since I installed version 1.1,1 item text in dropdown menus has ceased to work. Items are there, I can select them and the correct text shows once I've done so. But I'm not able to see what I'm selecting.

![empty](https://github.com/FlowFuse/node-red-dashboard/assets/5982179/eacebdf7-facd-4bc0-9164-7329fc11a2de)

### Expected Behavior

Text/labels should be shown for each item.

### Steps To Reproduce

Create a drodown menu and add some items. I have tried adding items directly from the edit dialog and passing via `msg.ui_update.options` and get the same result. Manually creating a "similar" component using a template works fine:

```vue
<template>
  <select v-model="selected">
    <option v-for="item in items" :key="item.value" :value="item.value">
      {{ item.text }}
    </option>
  </select>
</template>

<script>
export default {
  data() {
    return {
      selected: null,
      items: [
        { value: 1, text: 'Option 1' },
        { value: 2, text: 'Option 2' }
      ]
    };
  }
};
</script>
<style>
select, option {
    color: black;
    background-color: white;
}
</style>
````

Maybe some CSS problems? I have tried modifying various attributes I can't seem to get the labels to show anyways.

### Environment

- Dashboard version: 1.11.1
- Node-RED version: 3.1.11
- Node.js version: 16.20.2 (from official nodered docker image: `nodered/node-red:latest`)
- npm version: 8.19.4 (same as above)
- Platform/OS: Linux Lite 6.6
- Browser: Chrome 125.0.6422.60 and Firefox 127.0

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by postlund** [comment]
Oh, you are correct! It Resizing icons seems to affect what is shown in the menus (it was probably from my issue you found that snippet). Great, thanks! I disabled most of my nodes when debugging but I must have missed that one.

So, for reference. This is the original CSS:

```css
.v-navigation-drawer .v-icon {
    font-size: 5rem;
}

.v-navigation-drawer {
    width: 8rem !important;
}

.v-main {
    --v-layout-left: 8rem !important;
}

.v-list-item__content {
    display: none
}
```

The last class seems to be the offender here, as it also affects dropdown menus and possibly other cases as well. Limiting it to the navigation drawer seems to work:

```css
.v-navigation-drawer .v-list-item__content {
    display: none
}
```

@joepavitt Since you helped me with this, just wanted to give you a ping in case you decide to implement this natively.
